name: quaytest

on: push

env:
    ARTIFACT_NAME: myfile.txt

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: list the env
              run: export
            - name: show the time
              run: date
    job2:
        runs-on: macos-latest
        steps:
            - name: display the Macos versions
              run: sw_vers
            - name: checkout code
              uses: actions/checkout@v4.2.2
            - name: list the current directoty
              run: pwd;ls -al
            - name: upload the readme file
              uses: actions/upload-artifact@v4.4.3
              with: 
                  name: ${{ ARTIFACT_NAME }}
                  path: ./README.md
    job3:
        runs-on: ubuntu-latest
        container: 
            image: cypress/base:22.12.0
        steps:
            - name: check the Cypress Version
              run: npx cypress --version
    jobs4:
        needs: [job1,job2]
        runs-on: ubuntu-latest
        steps:
            - name: show the current date and time
              run: date
