name: quaytest

on: push

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: list the env
              run: export
            - name: show the time
              run: date
    job2:
        runs-on: macos-latest
        steps:
            - name: display the Macos versions
              run: sw_vers
    jobs3:
        needs: [job1,job2]
        runs-on: ubuntu-latest
        steps:
            - name: show the current date and time
              run: date
